---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: linuxander
type: Opaque
data:
  dbhost-name: [ENTER BASE64 ENCODED DATA HERE]
  django-db-name: [ENTER BASE64 ENCODED DATA HERE]
  root-pw: [ENTER BASE64 ENCODED DATA HERE]
  djangouser-name: [ENTER BASE64 ENCODED DATA HERE]
  djangouser-pw: [ENTER BASE64 ENCODED DATA HERE]
